spring:
  application:
    name: username-service
  profiles:
    default: dev
  datasource:
    url: ${FLYWAY_URL:jdbc:postgresql://localhost:5432/usernames}
    username: ${FLYWAY_USER:username}
    password: ${FLYWAY_PASSWORD:secret}
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 5
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080

logging:
  level:
    root: INFO

handles:
  blocklist:
    location: classpath:blocklist-sv.json

flyway:
  url: ${FLYWAY_URL:jdbc:postgresql://localhost:5432/usernames}
  user: ${FLYWAY_USER:username}
  password: ${FLYWAY_PASSWORD:secret}
  locations:
    - classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
